---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - courier.misospace.dev
  resources:
  - coderruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - courier.misospace.dev
  resources:
  - coderruns/finalizers
  verbs:
  - update
- apiGroups:
  - courier.misospace.dev
  resources:
  - coderruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - courier.misospace.dev
  resources:
  - laneprofiles
  verbs:
  - get
  - list
  - watch
